### ISSUE TITLE
Underscore-Express blows chunks when errors in included templates

### ISSUE THREAD

**Issue by cefn** [caseywebdev/underscore-express#2]
Thanks for underscore-express. 

It's a real inspiration and is already fixing some serious architectural issues for me, by being able to wrangle my own 'DSL' for my app's very specific templating needs.

However, there's a missing callback argument in the embedded call to render made by the include(...) function. Because there's no cb passed in, the sync error handling clause is hit and the node server gets taken down by errors in sub-templates.

To fix it, you just change the line...

    var str = render(path.resolve(dir, rel + '.' + ext), options);

...to read...

    var str = render(path.resolve(dir, rel + '.' + ext), options, cb);

...and then the error handling gets passed down the middleware path to the proper location.

**Comment by caseywebdev** [comment]
Thanks for the report! This should be fixed in `1.0.0`
