### ISSUE TITLE
Include cannot access variables in scope

### ISSUE THREAD

**Issue by cefn** [caseywebdev/underscore-express#3]
It looks like scope variables can't be accessed given the existing implementation of include, is that right?

I think it means that iteration like the following is impossible within a 'parent' template, since it's only the options which are made available to the subtemplate, and it's currently impossible to modify the options themselves.

```javascript
        _.forIn(questions, function(question, questionIdx){
            var answer = answers[questionIdx]
            print(include("editor_form_field"));
        })
```

**Comment by cefn** [comment]
I have a workaround which you may want to consider for the library, which allows the include line to look like this instead, by allowing an extra argument to include which is merged into the options before the embedded template is rendered...

    print(include("editor_form_field", {question:question,answer:answers[questionIdx]}));

Incidentally the need for ```print(include('something'))``` and the lack of scope visibility suggests that 'include' is the wrong term for the current implementation, and unlike the include which exists in EJS and its derivatives, it doesn't have the scope visibility which a literally 'included' fragment has.

**Comment by caseywebdev** [comment]
I like that. It's called `include` because generally you'd use it like this

```erb
<%= include('header') %>
This is the body!
<%= include('footer') %>
```

I'll add an option to merge in the second argument.

**Comment by caseywebdev** [comment]
Added in `1.0.1`

**Comment by cefn** [comment]
I recognise that `include` seems to describe the use case of including content in the html template, but often include is intended to mean that an external file is _included in the source_, (meaning both that it can optionally output as part of the current template, but also its code is evaluated in the current context within that template).

To be specific I might suggest `evaluate` would be a better name as it is a function which runs in isolation and simply returns a string (rather than adding content to the output stream), and is evaluated in isolation (rather than being provided access to current stack context) which is what the include calls of EJS or ejs-mate did. 

Of course you can use the print syntax `<%= %>` to turn any value (including a string return from `evaluate`)  into content included in the output, but it seems like semantic drift to commit this single use case into the function name. Just a thought and it won't take long for someone to figure out what it actually does given the simplicity of the API :)
